gnosisguild/zodiac-os

.github/workflows/prod-release.yaml, manifest-util.js, public/manifest.json
This creates a github action that will do the following on every release:
1. Build the extension
2. Modify the `version` field in the `manifest.json` file with the release's tag
3. Create the zip file
4. Upload to IPFS
5. Modify the release notes to include the IPFS hashes and links to the hash on a few different gateways.
@jfschwarz let me know if there's a way of including the functionality of `manifest-util.json` that seems better. A separate script file felt like the lightest touch to me.
=> Add github action for zipping and uploading to IPFS

README.md, public/manifest.json
The Zodiac Pilot extension is now available in the webstore, this adds the link to the readme. This also adds the latest release version to the `public/manifest.json` file so the published version matches the repo.
=> Update manifest version and add webstore link

extension/package.json, extension/public/manifest.json, extension/src/app.tsx, extension/src/browser/Drawer/ContractAddress/index.tsx, extension/src/browser/Drawer/ContractAddress/style.module.css, extension/src/browser/Drawer/RolePermissionCheck.tsx, extension/src/browser/Drawer/Submit.tsx, extension/src/browser/Drawer/Transaction.tsx, extension/src/browser/Drawer/index.tsx, extension/src/browser/Drawer/style.module.css, extension/src/browser/ProvideProvider.tsx, extension/src/components/Box/style.module.css, extension/src/components/Flex/style.module.css, extension/src/components/Toast/Toast.module.css, extension/src/components/Toast/index.tsx, extension/src/networks.ts, extension/src/providers/WrappingProvider.ts, extension/src/providers/useWalletConnect.ts, extension/src/settings/Connection/useSafeModuleInfo.ts, extension/src/types/index.ts, extension/yarn.lock, landing-page/public/manifest.json
This PR fixes a critical error when submitting multiple transactions. It used the wrong multi-send contract address and the wrong operation type (`call` instead of `delegatecall`).
While at it, I also made sure that errors on submit are shown to the user in a toast.
I also added a button to copy the batch transaction data to the clipboard, which might be useful for debugging purposes or when needing to use the transaction data in some way other than directly submitting it via WalletConnect.
=> fix: encoding error on batch submit

extension/src/settings/Connection/useSafeModuleInfo.ts, extension/src/utils/decodeRolesError.ts
The extension currently does not work when connecting with MetaMask. That is due to changes in the structure of the JavaScript error object that is thrown by MetaMask in case of reverts. 
This PR adjusts error decoding so we can again correctly detect the expected error in the dry run.
=> adjust error decoding to fix MetaMask dry run

extension/src/components/Field/index.tsx, extension/src/components/Field/style.module.css, extension/src/components/Select/ModSelect.tsx, extension/src/components/Select/index.tsx, extension/src/components/Select/style.module.css, extension/src/components/Tag/style.module.css, extension/src/settings/Connection/ConnectButton/index.tsx, extension/src/settings/Connection/ConnectButton/style.module.css, extension/src/settings/Connection/Edit.tsx, extension/src/settings/Connection/style.module.css, extension/src/settings/Connection/useZodiacModules.ts, extension/src/settings/index.tsx, extension/src/settings/style.module.css
Adjusting the UX on the edit page to be a little more user friendly
- added blockies to safe and mod selection
- made the 'Impersonated Safe' look a little more stout when connected, and made removing it a button instead of deleting from a text input
- adjusted the Connect Button to more closely match the new components below it
- error style reads a bit better
=> Edit Page UX

extension/src/components/Select/index.tsx, extension/src/providers/safe.ts, extension/src/settings/Connection/AvatarInput/index.tsx, extension/src/settings/Connection/AvatarInput/style.module.css, extension/src/settings/Connection/Edit.tsx, extension/src/settings/Connection/ModSelect/index.tsx
This adds an input / drop down element that allows users to paste in addresses or choose from safes they are owners of. If the wallet is not an owner of any safe, a standard input is used.
=> Direct connect UX improvements 

README.md, extension/src/providers/ProvideTenderly.tsx
The previous links only worked for authenticated members of our Tenderly org 🙈
=> fix tenderly simulation links

extension/src/transactionTranslations/index.ts, extension/src/transactionTranslations/uniswapMulticall.ts
The function used to check if a transaction was eligible for a translation (`findApplicableTranslation`) was broken.
A change is required in the translations. The `translate` function a `TransactionTranslation` should throw an error if a transaction cannot be translated.
=> fix: check if tx is eligible for translation

extension/src/bridge/host.ts, extension/src/bridge/iframe.ts, extension/src/browser/Frame.tsx, extension/src/providers/ForkProvider.ts
With the new connections design inside a drawer the user would intuitively expect that "account switching" behaves like it does in other dapps.
This change will emit 2 events each time a new connection/provider is used:
- accountsChanged
- chainChanged
This should follow the EIP-1193 specification.
https://www.loom.com/share/3ff7b7af12c24cccbe25a56b79c45a40
=> Account switching

extension/src/browser/ConnectionsDrawer/Edit/index.tsx, extension/src/browser/ConnectionsDrawer/Edit/style.module.css, extension/src/browser/ConnectionsDrawer/List/index.tsx, extension/src/browser/ConnectionsDrawer/List/style.module.css, extension/src/browser/ConnectionsDrawer/index.tsx, extension/src/browser/ConnectionsDrawer/style.module.css, extension/src/components/ConnectionBubble/index.tsx, extension/src/components/ConnectionBubble/style.module.css, extension/src/routing.ts
- all of the connection bubble is a single button / hover target
- clicking on the connection stack in the hover bubble takes u directly to the settings edit page
- brought back the connection item being a button (in an html semantic way, with no nested interactive elements)
- adjusted connection icon button to match square look of corner connection bubble
- adjusted edit layout to move less when switching between the list and edit views
- adjusted button padding
=> Connections drawer tweaks

extension/src/bridge/iframe.ts
In a recent app update Aura seems to have removed the generic injected wallet connector in their rainbow kit config. This caused Pilot to not be detected by Aura anymore.
We work around this by impersonating MetaMask when injecting into Aura.
=> Fix wallet connection for Aura

extension/src/providers/useWalletConnect.ts, extension/src/settings/Connection/ConnectButton/index.tsx, extension/src/settings/connectionHooks.tsx
This is a quick fix that will only make it work for existing connections. 
Due to the quite questionable design choices made by WalletConnect V2 we'll need to set the network BEFORE requesting the wallet connection. So we can no longer just read the chain ID from the wallet after connecting. This means we'll probably have to let the user manually select a chain as a first step.
=> fix walletconnect on non-mainnet chains

extension/.cspell.json, extension/src/browser/Drawer/index.tsx, extension/src/connections/ConnectionsDrawer/ChainSelect/index.tsx, extension/src/connections/ConnectionsDrawer/ChainSelect/style.module.css, extension/src/connections/ConnectionsDrawer/ConnectButton/index.tsx, extension/src/connections/ConnectionsDrawer/Edit/index.tsx, extension/src/connections/connectionHooks.tsx, extension/src/connections/useZodiacModules.ts, extension/src/providers/ProvideTenderly.tsx, extension/src/providers/readOnlyProvider.ts, extension/src/providers/useWalletConnect.ts, extension/src/safe/useSafeDelegates.ts, extension/src/safe/useSafesWithOwner.ts, extension/src/utils/decodeError.ts
This PR adds a field for setting the chain of a connection. So far we retrieved it from the connected wallet (metamask/walletconnect). Making it more explicit might clear confusions and surface problems when connected to wrong chains.
=> Add Chain select field to connection setup UI

extension/.cspell.json, extension/src/app.tsx, extension/src/bridge/SafeAppBridge.ts, extension/src/browser/Drawer/RolePermissionCheck.tsx, extension/src/browser/Drawer/Submit.tsx, extension/src/browser/Drawer/Transaction.tsx, extension/src/browser/Drawer/index.tsx, extension/src/browser/Drawer/style.module.css, extension/src/browser/ProvideProvider.tsx, extension/src/components/Address/index.tsx, extension/src/components/Address/style.module.css, extension/src/components/Button/index.tsx, extension/src/components/Button/style.module.css, extension/src/components/ConnectionBubble/index.tsx, extension/src/components/ConnectionStack/index.tsx, extension/src/connections/ConnectionsDrawer/Edit/index.tsx, extension/src/connections/ConnectionsDrawer/List/index.tsx, extension/src/connections/useConnectionDryRun.tsx, extension/src/injection.ts, extension/src/location.ts, extension/src/providers/WrappingProvider.ts
We now allow launching also if we don't have a connected Pilot wallet.
There are two cases we're handling:
- The Pilot wallet was never connected before, meaning `pilotAddress` is not set
- For now we disable role permission checks. (We could potentially enable them by querying an example role member of the specified role, but I left this for later)
- When submitting we request to connect the pilot account, thus lazily completing the connection
- The Pilot wallet was connected in the past, so the connection remembers that `pilotAddress`
- We simulate using this account and role permission checks will be available
- We request to connect that account once the user tries to submit 
For the lazy connect on submit flow, we're taking the user to the connection Edit panel. After clicking the …
=> Launch with unconnected Pilot wallet

extension/.prettierrc.cjs, extension/e2e/errorHandling.spec.ts, extension/e2e/mockWeb3.ts, extension/package.json, extension/pnpm-lock.yaml, extension/src/components/Alert/index.tsx, extension/src/components/Button/index.tsx, extension/src/components/Button/style.module.css, extension/src/components/RouteBubble/index.tsx, extension/src/components/index.ts, extension/src/connect/ConnectProvider.ts, extension/src/panel/routes/ConnectButton/index.tsx, extension/tailwind.config.js
This PR extends the Playwright setup to be able to interact with connected wallets and mock web3 events. It adds a baseline check that the correct message is shown when a wallet provider is locked while managed by pilot.
=> feat: handle account disconnects (lock wallet)

extension/setup-chrome-mock.ts, extension/src/background/sessionTracking.spec.ts, extension/src/background/simulationTracking.spec.ts
Before, listeners were kept for the whole test suite. This can lead to false positives/negatives and makes tests harder to debug when they fail.
=> chore: clear chrome mock listeners after each test

extension/src/inject/injectedScript/InjectedProvider.ts, extension/src/panel/pages/routes/edit.$routeId/EditRoute.spec.tsx, extension/src/panel/providers/injected-provider/ConnectProvider.ts, extension/src/panel/providers/injected-provider/port/createPort.ts, extension/src/panel/providers/injected-provider/useConnectProvider.tsx, extension/test-utils/mockRoute.ts
Fixes #263
@jfschwarz I couldn't reproduce the issue you've faced. AFAICT, all the messages end up where they should be, and the responses look OK. However, I see that Rabby (on my machine) doesn't show that it updated the chain. So, I wonder whether we only talk to ourselves and the message never goes through. Love to have a look together with you on this one to verify what is going on.
=> fix: switch chain not working

extension/src/connect/contentScripts/dApp.ts
=> fix: move ensureIframe method out of global scope

extension/esbuild.mjs, extension/src/connect/contentScripts/dApp.ts
There should be no harm in generally emitting IIFE wrapped build output.
=> fix: generally prevent global scope clashes

extension/src/components/inputs/Input.tsx, extension/src/components/inputs/Select.tsx, extension/src/panel/pages/ClearTransactionsModal.tsx, extension/src/panel/pages/routes/edit.$routeId/AvatarInput.tsx, extension/src/panel/pages/routes/edit.$routeId/EditRoute.spec.tsx, extension/src/panel/pages/routes/edit.$routeId/EditRoute.tsx, extension/src/panel/pages/routes/list/ListRoutes.spec.ts, extension/src/panel/pages/routes/list/Route.tsx
Relates to #389 
Replace the old transaction modal mechanism with a new one. Also, we now use our own components for select controls and they are more accessible.
=> chore: refactor transaction remove modal on edit route

extension/src/components/CopyToClipboard.spec.tsx, extension/src/components/CopyToClipboard.tsx
Fixes #417 
`BigInt` isn't natively handled by JSON serialization, so we must do it manually.
=> fix big int serialization

.cspell.json, configs/tailwind/package.json, configs/tailwind/tailwind.config.mjs, deployables/app/package.json, deployables/app/tailwind.config.ts, deployables/example-app/package.json, deployables/example-app/tailwind.config.ts, deployables/extension/package.json, deployables/extension/tailwind.config.js, deployables/landing-page/package.json, deployables/landing-page/tailwind.config.ts, pnpm-lock.yaml
Part of #469 
Extract a shared tailwind configuration to avoid stupid mistakes in individual deployable. Especially around including the styles of shared UI package.
=> chore: extract tailwind config

deployables/app/app/components/AvatarInput.tsx, deployables/app/app/components/index.ts, deployables/app/app/routes/edit-route.spec.ts, deployables/app/app/routes/edit-route.tsx, deployables/app/package.json, packages/ui/src/inputs/Select.tsx, pnpm-lock.yaml
=> feat: show avatar in companion app

deployables/app/app/components/wallet/ConnectWallet.tsx, deployables/app/app/components/wallet/WalletProvider.tsx, deployables/app/app/components/wallet/index.ts, deployables/app/app/routes/edit-route.$data.spec.ts, deployables/app/app/routes/edit-route.$data.tsx
=> feat(pilot-app): disconnect wallet

.github/workflows/live-tests.yaml, .github/workflows/prod-release.yaml, deployables/app/app/components/DebugRouteData.tsx, deployables/app/app/components/ZodiacMod.tsx, deployables/app/app/routes/edit-route.$data.tsx, deployables/app/package.json, deployables/extension/manifest-util.js, deployables/extension/src/inject/contentScript/main.ts, deployables/extension/src/manifest.template.json, packages/modules/src/removeAvatar.ts, packages/modules/src/updateRolesWaypoint.ts, packages/test-utils/src/renderFramework.tsx, pnpm-lock.yaml
=> feat(extension): make extension load companion app

deployables/extension/src/panel/pages/ClearTransactionsModal.tsx, deployables/extension/src/panel/pages/Root.spec.ts, deployables/extension/src/panel/pages/Root.tsx, deployables/extension/src/panel/pages/index.tsx
=> feat(extension): clear transaction when needed on route update

.github/workflows/app-preview.yaml, .github/workflows/tests.yaml, .gitignore, deployables/app/app/routes/edit-route.$data.spec.ts, deployables/app/app/routes/edit-route.$data.tsx, deployables/app/e2e/accountHandling/lockedAccount.spec.ts, deployables/app/e2e/accountHandling/unavailableWallet.spec.ts, deployables/app/e2e/accountHandling/wrongChain.spec.ts, deployables/app/e2e/connectWallet.ts, deployables/app/e2e/smoketest.spec.ts, deployables/app/e2e/utils/fixture.ts, deployables/app/e2e/utils/getExtensionPage.ts, deployables/app/e2e/utils/index.ts, deployables/app/e2e/utils/loadExtension.ts, deployables/app/package.json, deployables/app/playwright.config.ts, deployables/extension/.gitignore, deployables/extension/package.json, packages/test-utils/package.json, packages/test-utils/src/e2e/index.ts, packages/test-utils/src/e2e/mockWeb3.ts, packages/test-utils/src/e2e/waitFor.ts, pnpm-lock.yaml
=> chore(pilot-app): e2e for companion app

deployables/app/app/components/wallet/ConnectWalletFallback.tsx, deployables/app/app/components/wallet/Wallet.tsx, deployables/app/app/components/wallet/WalletProvider.tsx, deployables/app/app/components/wallet/index.ts, deployables/app/app/routes.ts, deployables/app/app/routes/connect.tsx, deployables/app/app/routes/edit-route.$data.spec.ts, deployables/app/app/routes/edit-route.$data.tsx, deployables/app/app/routes/intents.ts, deployables/app/e2e/utils/index.ts, deployables/app/tsconfig.json, deployables/extension/manifest-util.ts, deployables/extension/src/connect/contentScripts/dApp.ts, deployables/extension/src/manifest.template.json, packages/modules/src/removeAvatar.spec.ts, packages/modules/src/removeAvatar.ts, packages/test-utils/src/e2e/mockWeb3.ts
=> fix(pilot-app, extension): better optimistic updates and connection handling

deployables/extension/src/panel/execution-routes/getRoutes.ts, deployables/extension/src/panel/pages/$activeRouteId/transactions/Submit.tsx, packages/modules/src/createBlankRoute.spec.ts, packages/modules/src/createBlankRoute.ts, packages/modules/src/createEoaAccount.ts, packages/modules/src/updateChainId.spec.ts, packages/modules/src/updatePilotAddress.spec.ts, packages/modules/src/updateProviderType.spec.ts, packages/modules/src/updateProviderType.ts, packages/modules/src/updateStartingWaypoint.ts, packages/test-utils/src/creators/createMockEoaAccount.ts
Part of #469 
- fixes the "Connect wallet to submit" button behaviour
- also fixes an issue where EOA accounts got a chain into their prefixed address
=> fix(pilot-app, extension): submit connect wallet button not working

packages/modules/src/updateChainId.spec.ts, packages/modules/src/updateChainId.ts, packages/modules/src/updatePilotAddress.ts, packages/modules/src/updatePrefixedAddress.ts, packages/modules/src/updateProviderType.spec.ts, packages/modules/src/updateProviderType.ts, packages/test-utils/src/creators/createMockRoleWaypoint.ts
=> fix(pilot-app): handle EOA related updates better

deployables/app/app/components/wallet/Connect.tsx, deployables/app/app/components/wallet/ConnectWallet.tsx, deployables/app/app/routes/edit-route.$data.tsx
Fixes #693 
`ConnectKit` always resets the provider to the first configured network when connecting. So, every time we'd connect a provider, the chain configuration of a route would be reset. This isn't desirable. Now, your provider will switch to Ethereum regardless of what you've been on before, but at least you see that in the configuration, and you can switch back to the chain it should be on with one click.
=> fix(pilot-app): do not update chain id when a wallet connects

deployables/extension/src/background/rpcTracking.ts
Part of #582 
RPC tracking could get stuck when a tab would not respond. Now, each tab has 10 seconds to respond. After that the requests times out and can be tried again.
=> chore: timeout rpc tracking and track errors

deployables/app/app/components/wallet/Connect.tsx, deployables/app/app/components/wallet/ConnectWallet.tsx, deployables/app/app/components/wallet/EmptyAccount.tsx, deployables/app/app/components/wallet/LaunchConnectKit.tsx, deployables/app/app/components/wallet/Wallet.tsx, deployables/app/app/components/wallet/WalletDisconnected.tsx, deployables/app/app/components/wallet/WrongAccount.tsx, deployables/app/app/routes/submit.$route.$transactions.tsx, deployables/app/e2e/accountHandling/lockedAccount.spec.ts, deployables/app/e2e/accountHandling/unavailableWallet.spec.ts
part of #703 
wagmi's `useReconnect` hook doesn't do what we assumed, and as we're already using `useAutoReconnect` we'll basically never need it. Instead for triggering a full wallet reconnect, we can simply pop open the connectkit modal.
=> fix: wallet connection UI on the submit page 

deployables/extension/src/inject/injectedScript/main.ts, deployables/extension/src/inject/injectedScript/maskMetaMaskAnnouncement.ts
Part of #484 
This PR partially resolves the issue. At least it is now possible to connect to etherscan.io **at all**. What is still not working properly is connecting to etherscan when the MetaMask extension is **also** enabled. This fix **only** works if the extension is disabled.
=> fix(extension): make it possible to connect to etherscan

deployables/extension/esbuild.mjs, deployables/extension/src/companion/contentScripts/fork-support.spec.ts, deployables/extension/src/companion/contentScripts/fork-support.ts, deployables/extension/src/companion/contentScripts/main.spec.ts, deployables/extension/src/companion/contentScripts/main.ts, deployables/extension/src/manifest.template.json
This PR splits the content script for the companion app. All listeners are registered on `document_start`, and only the message to guarantee an up-to-date fork is run at the end.
=> fix(extension): register listeners on document start

deployables/app/app/routes/submit/$route.$transactions.tsx
Now that the Safe Transaction Service is working again, we should enqueue by default, rather than override
=> fix: remove the temp workaround while the safe tx service was down

deployables/app/app/routes/edit/list-routes.spec.ts, packages/safe/package.json, packages/safe/src/kits.ts, pnpm-lock.yaml
After Safe has finally released their packages' ESM versions, we can eliminate some hacks.
=> chore: remove safe init hacks

deployables/app/app/simulation/server/api.ts, deployables/app/app/vnet/server/api.ts, deployables/app/app/vnet/server/getVnetTransactions.ts
By default the tenderly vnet API only returns 10 transactions at a time. By setting the page size explicitly this PR increases it so that the balances page will reflect all balance updates also for larger recorded bundles
=> fix(pilot-app): increase vnet transactions page size

deployables/extension/src/panel/pages/$activeRouteId/transactions/Transactions.spec.ts, deployables/extension/src/panel/pages/useLaunchRoute.ts
Closes #1348
This PR addresses a persistent UX issue described in #1348, where the extension would not switch to the newly created account after the user completed the creation flow.
The problem was caused by missing handling in `useLaunchRoute` for the case where a new route is created (i.e. the `routeId` differs from the current `activeRouteId`). While the `onLaunch` callback was invoked, no navigation was triggered, leaving the extension and UI in an inconsistent state.
- Updated `useLaunchRoute` to differentiate between updating an existing account vs. creating a new one.
- When a new route is detected, we now:
- Invoke the `onLaunch` callback (as before),
- Immediately navigate to the corresponding route.
- For existing routes with pending transactions, we preserve the existing …
=> fix: Extension is not switched to new account after creating it

packages/ui/src/inputs/AddressSelect.tsx
=> fix: make sure to still show value even if it does not exist in options

deployables/app/app/routes-ui/ChainSelect.tsx, packages/chains/src/const.ts
small fix after we enabled some additional chains without ser query support with https://github.com/gnosisguild/zodiac-pilot/pull/1639.
we currently can't query routes for unichain, world chain and bob. but we can still let users manually build execution routes for these chains and import them into Pilot using https://github.com/gnosisguild/build-pilot-route.
to avoid confusing users we now hide these "half-supported" chains. they will be displayed and supported for manually imported routes but won't be suggested for route building to regular Pilot users.
=> fix: hide chains without ser query support

deployables/app/app/routes/account/routes.tsx
Fixes #1930 
To be removed after v3.17.0 of the extension is available in the Chrome web store.
=> chore(zodiac-os): remove mutliple-routes feature flag

deployables/app/app/routes-ui/Waypoints.tsx, packages/ui/src/addresses/Address.tsx
=> fix(zodiac-os): ens names should not overflow waypoints

README.md, deployables/app/app/components/pilotStatus/PilotStatus.tsx, deployables/app/app/components/pilotStatus/index.ts, deployables/app/app/components/pilotStatus/useIsExtensionInstalled.tsx, deployables/app/app/routes/launch/$prefixedAvatarAddress.$accountLabel/launch.tsx, deployables/app/app/routes/tokens/index.tsx
We now show clearly if the Zodiac Pilot extension is not yet installed and offer a link to the Chrome Web Store.
This is getting more important as Zodiac OS becomes the primary entrypoint and the extension acts more to progressively enhance the user experience for Zodiac OS users. Also in the context of Railgun Connect (#1957), first-time users are now guided clearly through the initial set up flow.
=> feat(companion-app): extension onboarding
