src/browser/AddressBar.tsx
src/browser/index.module.css
src/browser/index.tsx
src/components/Address/index.tsx
src/components/Address/style.module.css
src/components/Box/style.module.css
src/components/Flex/index.tsx
src/components/Flex/style.module.css
src/components/Select/index.tsx
src/global.css
src/settings/index.tsx
src/settings/style.module.css

Browser page styling & disconnect button

---

src/browser/index.module.css
src/components/AppPicker/style.module.css
src/components/Button/style.module.css
src/global.css

Adds a little more verve to buttons and inputs

---

src/browser/AddressStack.tsx
src/browser/index.module.css
src/components/Address/index.tsx
src/components/Address/style.module.css
src/components/AppPicker/style.module.css
src/components/Box/index.tsx
src/components/Box/style.module.css
src/components/Button/style.module.css
src/global.css

preview movie:
https://user-images.githubusercontent.com/6718506/145094010-cc31f148-ded6-404d-8fbc-1aa62f3d1c13.mov

Changes address stack style, adds hover labels

---

src/browser/index.module.css
src/browser/index.tsx
src/components/BlockButton/style.module.css
src/settings/Connection/Select.tsx
src/settings/Connection/style.module.css

edit button and launch page style tweaks

---

extension/src/components/Address/index.tsx
extension/src/settings/Connection/ConnectButton/index.tsx
extension/src/settings/Connection/ConnectButton/style.module.css
extension/src/settings/style.module.css

Initial State
Wrong wallet
Wrong network

Styling metamask state

---

extension/src/app.tsx
extension/src/browser/Drawer/RolePermissionCheck.tsx
extension/src/browser/Drawer/Submit.tsx
extension/src/components/Toast/Toast.module.css
extension/src/components/Toast/index.tsx

Style Toast

---

landing-page/README.md

The landing page appears to have outdated CSS for some reason, so I'm using this PR kick off a new deployment of it.

Update Landing Page readme

---

extension/src/browser/Drawer/RolePermissionCheck.tsx
extension/src/browser/Drawer/SimulatedExecutionCheck.tsx
extension/src/browser/Drawer/Transaction.tsx
extension/src/browser/Drawer/style.module.css

I also gave each box more breathing room by having them each on their own line.

Hide Role Check when not using Role mod

---

extension/src/browser/Drawer/ContractAddress/index.tsx
extension/src/browser/Drawer/ContractAddress/style.module.css
extension/src/browser/Drawer/Transaction.tsx
extension/src/browser/Drawer/style.module.css
extension/src/components/AppPicker/index.tsx
extension/src/components/Flex/index.tsx
extension/src/components/Select/ModSelect.tsx
extension/src/components/Select/style.module.css
extension/src/global.css
extension/src/networks.ts
extension/src/providers/useWalletConnect.ts
extension/src/settings/Connection/ConnectButton/index.tsx
extension/src/settings/Connection/ConnectButton/style.module.css
extension/src/settings/Connection/Edit.tsx
extension/src/settings/Connection/style.module.css

Just some small design changes:
- make contract blocks same dimensions as blockies in address stack
- adjust design of the transaction value (ETH/xDAI) display

Harmonize some styles in the transaction header

---

extension/src/components/Address/index.tsx
extension/src/components/Address/style.module.css
extension/src/components/ConnectionBubble/index.tsx
extension/src/components/ConnectionBubble/style.module.css
extension/src/components/ConnectionStack/index.tsx
extension/src/settings/Connection/AvatarInput/index.tsx
extension/src/settings/Connection/Edit.tsx
extension/src/settings/Connection/ModSelect/index.tsx

Direct Exec — UI tweaks

---

extension/src/browser/Drawer/RolePermissionCheck.tsx
extension/src/browser/Drawer/index.tsx
extension/src/utils/decodeRolesError.ts

fix direct exec bugs

---

extension/src/browser/ConnectionsDrawer/index.tsx
extension/src/components/ConnectionBubble/index.tsx
extension/src/providers/useWalletConnect.ts

Fixing some bugs that surfaced after releasing the WalletConnect upgrade

WalletConnect V2 bugfixes

---

.github/workflows/prod-release.yaml

temporarily disable ipfs release

disable failing release jobs

---

extension/src/integrations/safe/kits.ts
extension/src/providers/ProvideTenderly.tsx

- fix a bug when simulating on Polygon fork
- fix a bug when simulating through an owner (connections without Zodiac mod)

Fix simulation issues

---

extension/src/browser/Drawer/RolePermissionCheck.tsx
extension/src/contentScript.ts
extension/src/injection.ts
extension/src/providers/ForkProvider.ts

co-exist with Rabby

---

extension/src/bridge/InjectedProvider.ts

Generally impersonate MetaMask for improved compatibility across apps

generally impersonate metamask

---

extension/src/transactionTranslations/uniswapMulticall.ts

This reverts commit 5222d1ceb294879add1cf8ac0a63ade13065061a, reversing changes made to 46e6026eb414a22d6c26d20b05fe1dcf0866fd76.

Revert "Merge pull request #141 from gnosisguild/unfold-multicall-clear-eth"

---

example-app/.gitignore
example-app/app/root.jsx
example-app/package-lock.json
example-app/package.json
example-app/server.js
example-app/vite.config.js

Part of #143 
This PR adds the scaffolding for a remix app that shall be extended to ultimately used for e2e tests of the pilot browser plugin.

bootstrap example app

---

example-app/.prettierrc
example-app/app/root.tsx
example-app/app/tailwind.css
example-app/app/transfer/Balance.tsx
example-app/app/transfer/Transfer.tsx
example-app/app/transfer/index.ts
example-app/package-lock.json
example-app/package.json
example-app/postcss.config.js
example-app/tailwind.config.ts
example-app/tsconfig.json
example-app/vite.config.js

Part of #143 
Show the current balance of the connected wallet

feat: show balance in example app

---

example-app/app/Connect.tsx
example-app/app/components/Input.tsx
example-app/app/components/index.ts
example-app/app/root.tsx
example-app/app/transfer/Balance.tsx
example-app/app/transfer/Transfer.tsx
example-app/package-lock.json
example-app/package.json
example-app/tsconfig.json

Part of #143 
add controls to initiate swap

feat: swap controls for the example app

---

extension/src/bridge/SafeAppBridge.ts
extension/src/providers/ForkProvider.ts

Fix Safe app connection to nexus and stakewise

---

example-app/app/clients/ClientProps.ts
example-app/app/clients/PublicClient.tsx
example-app/app/clients/WalletClient.tsx
example-app/app/clients/WebsocketClient.tsx
example-app/app/components/Checkbox.tsx
example-app/app/components/index.ts
example-app/app/root.tsx

Part of #143 
~For a reason, I don't quite get displaying the block size breaks (at least) or the local interaction with Anvil. If this component renders, transactions will be stuck in a pending state.~
Nevermind, it had something to do with my `nonce` clearing all pending transaction and resetting the `nonce` value did the trick.

feat: make it possible to turn batching on and off

---

example-app/app/clients/PublicClient.tsx
example-app/app/clients/WalletClient.tsx
example-app/app/clients/WebsocketClient.tsx
example-app/app/components/Checkbox.tsx
example-app/app/root.tsx

Closes #143 
For now, these are the final touches to the testing app. More will most likely come when we start using it or actual tests.

chore: clean up component composition

---

.github/workflows/playwright.yml
example-app/app/root.tsx
example-app/package-lock.json
example-app/package.json
extension/.env.template
extension/e2e/fixture.ts
extension/e2e/getExtensionPage.ts
extension/e2e/smoketest.spec.ts
extension/e2e/waitFor.ts
extension/package.json
extension/playwright.config.ts
extension/src/background/index.ts
extension/src/monitor/injectedScript.ts

First version of an E2E test where the chrome extension is opened

chore: open zodiac extension in test

---

extension/e2e/accountHandling.spec.ts
extension/e2e/mockWeb3.ts
extension/src/components/Alert/index.tsx
extension/src/panel/routes/ConnectButton/index.tsx

Make sure that locked accounts can be reconnected or disconnected

feat: reconnect account

---

extension/setup-chrome-mock.ts
extension/src/connect/ConnectProvider.ts
extension/src/panel/port.ts
extension/src/panel/providers/ForkProvider.ts
extension/src/utils/getActiveTab.ts
extension/src/utils/index.ts
extension/test-utils/index.ts
extension/test-utils/mockActiveTab.ts
extension/test-utils/mockRoute.ts
extension/test-utils/render.tsx
extension/vitest.config.ts
extension/vitest.setup.mts

chore: extract get current tab utility

---

extension/src/panel/providers/injected-provider/port/createPortWhenTabIsReady.ts
extension/src/utils/sendMessageToTab.spec.ts
extension/src/utils/sendMessageToTab.ts

fix: wait for page reload when sending message to tab fails

---

extension/src/panel/integrations/zodiac/fetchZodiacModules.ts
extension/src/panel/integrations/zodiac/index.ts
extension/src/panel/integrations/zodiac/useZodiacModules.ts
extension/src/panel/pages/routes/edit.$routeId/EditRoute.spec.tsx
extension/src/panel/pages/routes/edit.$routeId/EditRoute.tsx
extension/src/panel/pages/routes/edit.$routeId/ZodiacMod.tsx
extension/src/utils/formData.ts

Push another data fetching concern into the loader of the "Edit route" route.

chore: load zodiac modules in loader

---

extension/src/panel/pages/$activeRouteId/transactions/Submit.tsx
extension/src/panel/pages/routes/edit.$routeId/EditRoute.spec.tsx

fix: 404 when clicking button on transactions

---

extension/src/panel/pages/routes/edit.$routeId/EditRoute.spec.tsx
extension/src/panel/pages/routes/edit.$routeId/EditRoute.tsx

fix: ensure active route when deleting the currently active one

---

.prettierignore
extension/package.json
pnpm-lock.yaml

fix: submit through walletconnected Safe

---

extension/src/panel/providers-ui/ProvideProvider.tsx

fix: simulation success reported for reverts

---

extension/src/components/toasts/Toast.tsx
extension/src/components/toasts/errorToast.tsx
extension/src/components/toasts/infoToast.tsx
extension/src/components/toasts/successToast.tsx

Fixes #416 
adds a max-height for toasts and also resolves some layout issues coming from a dep update.

fix: toast layout issues

---

extension/src/panel/pages/$activeRouteId/index.tsx

fix: action for active route was not registered

---

extension/src/components/toasts/Toast.tsx
extension/src/components/toasts/ToastProps.ts
extension/src/components/toasts/errorToast.tsx
extension/src/inject/bridge/index.ts
extension/src/inject/bridge/useBridgeError.ts
extension/src/inject/bridge/useProviderBridge.spec.tsx
extension/src/panel/pages/_index/NoRoutes.spec.ts
extension/src/panel/pages/_index/NoRoutes.tsx
extension/src/panel/pages/routes/Routes.spec.ts
extension/src/panel/pages/routes/Routes.tsx
extension/src/panel/pages/routes/index.tsx
extension/test-utils/render.tsx
extension/test-utils/wallet/index.ts
extension/test-utils/wallet/mockProviderRequest.ts

fix: endless spinner when connecting a fresh extension

---

deployables/app/wrangler.toml

chore: update wrangler.toml

---

deployables/app/app/components/ChainSelect.tsx
deployables/app/app/components/index.ts
deployables/app/app/routes/edit-route.spec.ts
deployables/app/app/routes/edit-route.tsx
deployables/app/package.json
deployables/app/tsconfig.cloudflare.json
deployables/app/tsconfig.json
deployables/app/vite.config.ts
deployables/app/vitest.setup.ts
deployables/extension/package.json
packages/chains/package.json
packages/schema/package.json
packages/test-utils/package.json
pnpm-lock.yaml

feat: show chain select in companion app

---

deployables/app/app/components/AvatarInput.tsx
deployables/app/app/entry.server.tsx
deployables/app/app/routes.ts
deployables/app/app/routes/$account.$chainId.available-safes.ts
deployables/app/app/routes/$account.availableSafes.ts
deployables/app/app/routes/edit-route.spec.ts
deployables/app/app/routes/edit-route.tsx
deployables/app/eslint.config.mjs
deployables/app/package.json
deployables/app/workers/app.ts
deployables/extension/package.json
deployables/extension/src/panel/integrations/safe/index.ts
deployables/extension/src/panel/integrations/safe/waitForMultisigExecution.ts
packages/chains/src/const.ts
packages/safe/eslint.config.mjs
packages/safe/package.json
packages/safe/src/index.ts
packages/safe/src/kits.ts
packages/safe/tsconfig.json
packages/test-utils/src/renderFramework.tsx
pnpm-lock.yaml

feat(pilot-app): offer available safes

---

deployables/app/app/components/ZodiacMod.tsx
deployables/app/app/routes/edit-route.$data.spec.ts

feat(pilot-app): make it possible to configure the v2 role key

---

deployables/app/app/routes.ts
deployables/app/app/routes/edit-route.$data.tsx
deployables/app/app/routes/new-route.ts
deployables/app/app/utils/editRoute.ts
deployables/app/app/utils/index.ts
packages/modules/package.json
packages/modules/src/createBlankRoute.spec.ts
packages/modules/src/createBlankRoute.ts
packages/modules/src/createSafeWaypoint.ts
packages/modules/src/index.ts
packages/schema/src/routeSchema.ts
packages/test-utils/src/creators/createMockSafeAccount.ts
pnpm-lock.yaml

feat(pilot-app): make it possible to create a new route

---

packages/modules/src/updateRolesWaypoint.spec.ts
packages/modules/src/updateRolesWaypoint.ts

feat(pilot-app): make sure a role update updates also the route endpoint

---

.github/workflows/app-preview.yaml
deployables/app/app/entry.client.tsx
deployables/app/app/root.tsx
deployables/app/app/routes/edit-route.$data.tsx
deployables/app/app/routes/new-route.ts
deployables/app/app/utils/editRoute.ts
deployables/app/package.json
deployables/app/vite.config.ts
pnpm-lock.yaml

chore: sentry for companion app

---

deployables/app/app/routes/edit-route.$data.spec.ts
deployables/app/app/routes/edit-route.$data.tsx
deployables/app/app/routes/intents.ts
deployables/app/app/utils/dryRun/JsonRpcError.ts
deployables/app/app/utils/dryRun/decodeError.ts
deployables/app/app/utils/dryRun/dryRun.ts
deployables/app/app/utils/dryRun/handleRolesV1Error.ts
deployables/app/app/utils/dryRun/handleRolesV2Error.ts
deployables/app/app/utils/dryRun/index.ts
deployables/app/app/utils/dryRun/isSmartContractAddress.ts
deployables/app/app/utils/dryRun/maybeGetRoleId.ts
deployables/app/app/utils/dryRun/wrapRequest.ts
deployables/app/app/utils/index.ts
deployables/app/package.json
deployables/app/vitest.config.ts
packages/modules/src/getRolesWaypoint.ts
packages/modules/src/index.ts
packages/test-utils/src/renderFramework.tsx
pnpm-lock.yaml

feat(pilot-app): dry run in companion app

---

deployables/extension/src/panel/pages/routes/RemoveButton.tsx
deployables/extension/src/panel/pages/routes/edit.$routeId/EditRoute.tsx
deployables/extension/src/panel/pages/routes/list/ListRoutes.spec.ts
deployables/extension/src/panel/pages/routes/list/ListRoutes.tsx
deployables/extension/src/panel/pages/routes/list/Route.tsx
deployables/extension/src/panel/pages/routes/list/intents.ts

feat(pilot-app): make it possible to remove a route from the routes overview

---

deployables/app/app/routes/edit-route.$data.tsx

We've upgraded the Cloudflare workers, so the deployment should work again.

chore(pilot-app): bring back route debugging

---

deployables/app/app/components/wallet/ConnectWallet.tsx
deployables/app/app/components/wallet/WalletProvider.tsx
deployables/app/app/components/wallet/index.ts
deployables/app/app/routes/edit-route.$data.tsx
pnpm-lock.yaml

Reverts gnosisguild/zodiac-pilot#609

Revert "chore(deps): update dependency wrangler to v3.104.0"

---

deployables/app/app/routes/tokens/index.tsx
deployables/extension/esbuild.mjs
deployables/extension/src/background/enableExternalPanelOpen.spec.ts
deployables/extension/src/background/enableExternalPanelOpen.ts
deployables/extension/src/companion/contentScripts/main.ts
deployables/extension/src/companion/injectedScripts/main.ts
deployables/extension/src/monitor/injectedScript/main.ts
packages/messages/src/companionApp/editRoute.ts
packages/messages/src/extension/connect.ts

fix(pilot-app): make sure a wallet is connected

---

deployables/app/app/routes/edit-route.$data.tsx
deployables/app/app/utils/dryRun/dryRun.ts
packages/ui/src/alerts/Success.tsx
packages/ui/src/alerts/index.ts

fix(pilot-app): dry run fails when no roles are used

---

deployables/extension/src/inject/contentScript/main.ts
deployables/extension/src/utils/isValidTab.ts

fix(extension): do not try to open port to edit route page

---

deployables/app/app/components/wallet/Wallet.tsx
deployables/app/app/components/wallet/WalletProvider.tsx
deployables/app/app/components/wallet/index.ts
deployables/app/app/routes/edit-route.$data.tsx
deployables/app/app/routes/tokens/index.tsx

fix(pilot-app): auto connect wallet

---

deployables/app/app/routes/edit-route.$data.spec.ts
deployables/app/app/routes/edit-route.$data.tsx

feat(pilot-app): rename save

---

deployables/app/app/routes/edit-route.$data.tsx

feat(pilot-app): use route label in title

---

deployables/app/app/components/wallet/ConnectWallet.tsx

fix(pilot-app): auto connect on new route

---

.cspell.json
deployables/app/app/balances/client/useTokenBalances.ts
deployables/app/app/balances/types.ts
deployables/app/app/routes.ts
deployables/app/app/routes/tokens/balances/balances.spec.ts
deployables/app/app/routes/tokens/balances/balances.tsx
deployables/app/app/routes/tokens/send.spec.ts
deployables/app/app/routes/tokens/send/TokenValueInput.tsx
deployables/app/app/routes/tokens/send/send.tsx
packages/ui/src/Table.tsx
packages/ui/src/values/TokenValue.tsx

feat(pilot-app): send button on balances page

---

deployables/extension/src/panel/pages/$activeRouteId/transactions/Transactions.spec.ts
deployables/extension/src/panel/pages/$activeRouteId/transactions/Transactions.tsx

feat(extension): add means to open the send and balances view from the extension

---

deployables/app/app/balances/types.ts

fix(companion-app): allow time_at to be null

---

deployables/app/app/balances/server/api.ts
deployables/app/app/balances/server/getDeBankChainId.ts
deployables/app/app/balances/server/getTokenBalances.ts
deployables/app/app/balances/types.ts
deployables/app/app/routes/Sidebar.tsx

fix(companion-app): map internal chain id to debank chain id

---

deployables/extension/src/background/companionEnablement.spec.ts
deployables/extension/src/background/companionEnablement.ts
deployables/extension/src/companion/contentScripts/main.spec.ts
deployables/extension/src/companion/contentScripts/main.ts
deployables/extension/src/panel/port-handling/PortContext.tsx
deployables/extension/src/panel/port-handling/index.ts
deployables/extension/src/panel/port-handling/useCompanionAppPort.spec.ts
deployables/extension/src/panel/port-handling/useCompanionAppPort.ts
deployables/extension/src/utils/isValidTab.ts
deployables/extension/src/utils/sendMessageToTab.ts
packages/messages/src/companionApp/editRoute.ts
packages/messages/src/extension/connect.ts

feat(extension): extension groundwork for companion app status indicator

---

deployables/app/app/components/AvatarInput.tsx
deployables/app/app/components/ChainSelect.tsx
deployables/app/app/components/Page.tsx
deployables/app/app/routes.ts
deployables/app/app/routes/create/finish.tsx
deployables/app/app/routes/create/select-route.tsx
deployables/app/app/routes/create/start.tsx
deployables/app/app/routes/edit/edit-route.$data.spec.ts
deployables/app/app/routes/edit/edit-route.$data.tsx
deployables/app/app/routes/layout.tsx
packages/modules/src/getStartingWaypoint.ts
packages/modules/src/getWaypoints.ts
packages/modules/src/index.ts
packages/schema/src/index.ts
packages/schema/src/routeSchema.ts
packages/ui/src/Form.tsx

feat(pilot-app): automatic route discovery

---

deployables/app/app/routes/$address.$chainId/available-safes.ts
deployables/app/app/routes/edit/edit-route.$data.spec.ts

chore(pilot-app): load available safes through ser-kit

---

deployables/app/app/routes/create/select-route.tsx
packages/ui/src/addresses/Address.tsx
packages/ui/src/addresses/shortenAddress.ts

chore(pilot-app): light mode for route selection

---

deployables/app/app/components/AvatarInput.tsx
deployables/app/app/components/Page.tsx
deployables/app/app/components/wallet/ConnectWalletButton.tsx
deployables/app/app/components/wallet/LaunchConnectKit.tsx
deployables/app/app/components/wallet/index.ts
deployables/app/app/routes.ts
deployables/app/app/routes/create/layout.tsx
deployables/app/app/routes/create/start.spec.ts
deployables/app/app/routes/create/start.tsx
deployables/app/app/routes/layout.tsx
deployables/extension/src/companion/contentScripts/main.spec.ts
deployables/extension/src/companion/contentScripts/main.ts
deployables/extension/src/panel/pages/useSaveRoute.ts
packages/form-data/src/getHexString.ts
packages/form-data/src/index.ts
packages/messages/src/companionApp.ts
packages/ui/src/Form.tsx
packages/ui/src/addresses/Address.tsx
packages/ui/src/inputs/Select.tsx

feat(pilot-app,extension): new entry to create account

---

deployables/app/app/components/AvatarInput.tsx
deployables/app/app/routes-ui/ChainSelect.tsx
deployables/app/app/routes/create/start.tsx
deployables/app/app/routes/edit/edit-route.$data.spec.ts
deployables/app/app/routes/edit/edit-route.$data.tsx
deployables/app/app/routes/edit/intents.ts
deployables/app/app/routes/edit/list-routes.spec.ts
packages/ui/src/inputs/AddressInput.tsx

feat(pilot-app): make it possible to update the initiator and the avatar of routes

---

deployables/app/app/routes-ui/ChainSelect.tsx
deployables/app/app/routes/edit/edit-route.$data.tsx
deployables/app/app/routes/edit/intents.ts

feat(pilot-app): make it possible to update the chain

---

deployables/app/app/components/AvatarInput.tsx
deployables/app/app/components/InitiatorInput.tsx
deployables/app/app/components/KnownFromRoutes.tsx
deployables/app/app/components/index.ts
deployables/app/app/routes-ui/Routes.tsx
deployables/app/app/routes-ui/Waypoints.tsx
deployables/app/app/routes/create/start.spec.ts
deployables/app/app/routes/create/start.tsx
deployables/app/app/routes/edit/edit-route.$data.tsx
deployables/app/app/routes/edit/list-routes.tsx
deployables/app/vitest.setup.ts
packages/ui/src/Form.tsx
packages/ui/src/addresses/Address.tsx
packages/ui/src/buttons/BaseButton.tsx

- Slimmer layout
- better keyboard nav
- auto-select first route and scroll selected route into view

chore(pilot-app): small edit ux improvements

---

deployables/app/app/routes/create/start.spec.ts
deployables/app/app/routes/create/start.tsx
deployables/app/app/routes/edit/edit-route.$data.spec.ts
deployables/app/app/routes/edit/list-routes.tsx
deployables/app/app/utils/dryRun/dryRun.ts
deployables/app/app/utils/dryRun/index.ts
deployables/app/app/utils/dryRun/isSmartContractAddress.ts

feat(pilot-app): check whether account is a smart contract before creating a route

---

deployables/app/app/components/navigation/Navigation.tsx
deployables/app/app/routes/edit/$data/edit-route.tsx
deployables/app/app/routes/layout.tsx
deployables/app/app/routes/tokens/balances/balances.tsx
deployables/app/app/routes/tokens/balances/layout.tsx
deployables/app/app/routes/tokens/send/layout.tsx
packages/modules/src/createAccount.spec.ts

feat(pilot-app): show connected wallet on more pages

---

deployables/app/app/components/wallet/Connected.tsx
deployables/app/app/components/wallet/SwitchChain.tsx
deployables/app/app/components/wallet/WalletDisconnected.tsx
deployables/app/app/components/wallet/WrongAccount.tsx
deployables/app/app/routes-ui/Connection.tsx
deployables/app/app/routes-ui/Routes.tsx
deployables/app/app/routes-ui/Waypoints.tsx
deployables/app/app/routes/create/start.tsx
deployables/app/app/routes/edit/$data/edit-route.tsx
deployables/app/app/routes/edit/list-routes.tsx
deployables/app/app/routes/layout.tsx
deployables/app/app/routes/submit/$route.$transactions.tsx
deployables/app/app/routes/submit/layout.tsx
deployables/app/app/routes/tokens/send/send.tsx
packages/ui/src/Form.tsx
packages/ui/src/alerts/BaseAlert.tsx
packages/ui/src/alerts/Warning.tsx
packages/ui/src/inputs/InputLayout.tsx
packages/ui/src/inputs/Select.tsx
packages/ui/src/overlays/Popover.tsx
packages/ui/src/overlays/index.ts

feat(pilot-app): show route on sign page

---

deployables/landing-page/.gitignore
packages/safe/src/kits.ts

fix(extension): add back esm interop for safe packages

---

deployables/app/app/routes/edit/$routeId.$data/edit-route.spec.ts
deployables/app/app/routes/edit/$routeId.$data/edit-route.tsx
deployables/app/app/routes/edit/$routeId.$data/intents.ts

fix(pilot-app): remove dry run

---

.github/workflows/live-tests.yaml
deployables/app/e2e/edit-route/fixture.ts
deployables/app/e2e/edit-route/saveRoute.spec.ts
deployables/app/e2e/smoketest.spec.ts
deployables/app/e2e/utils/loadExtension.ts

Needs https://github.com/gnosisguild/zodiac-pilot/pull/782

chore: add new save route e2e test

---

deployables/app/app/root.tsx
deployables/app/app/routes-ui/Routes.tsx

fix(pilot-app): scrolling on edit page

---

deployables/extension/src/panel/pages/$activeRouteId/ActiveRoute.tsx

fix(extension): do not prevent render on internal tabs

---

deployables/app/app/components/pilotStatus/useActiveWhenVisible.ts
deployables/app/app/components/pilotStatus/useDisconnectWhenUnreachable.ts
deployables/app/app/components/pilotStatus/usePingWhileDisconnected.ts
deployables/app/app/routes/tokens/send/send.spec.ts
deployables/extension/src/panel/pages/useLaunchRoute.ts
deployables/extension/src/panel/pages/useSaveRoute.ts
deployables/extension/src/panel/port-handling/usePilotPort.ts

chore(pilot-app): only ping when visible

---

deployables/app/app/routes/submit/$route.$transactions/sign.spec.ts
deployables/app/app/routes/submit/$route.$transactions/sign.tsx

feat(pilot-app): disable sign when route is invalid

---

deployables/app/app/routes/submit/$route.$transactions/sign.spec.ts
deployables/app/app/routes/submit/$route.$transactions/sign.tsx
deployables/app/package.json
deployables/app/vitest.setup.ts
pnpm-lock.yaml

feat(pilot-app): disable sign when permission checks fail

---

deployables/app/app/balances/types.ts
deployables/app/app/simulation/types.ts

fixes this error:
https://app.pilot.gnosisguild.org/submit/eyJhdmF0YXIiOiJnbm86MHg0NThjZDM0NWI0YzA1ZThkZjM5ZDBhMDcyMjBmZWI0ZWMxOWY1ZTZmIiwiaWQiOiJ0dll5cWU3ME9jVzA0Yzd0N3owYWkiLCJpbml0aWF0b3IiOiJlb2E6MHg0OGE5ZDA5NTNjODk1OWFlYjE5YmE1NWY1YzA0YjBhNTRjODQ4MjNjIiwibGFiZWwiOiJHbm9zaXMgREFPIEdDIiwibGFzdFVzZWQiOjE3NDIzMDU3NDUxMzMsIndheXBvaW50cyI6W3siYWNjb3VudCI6eyJhZGRyZXNzIjoiMHg0OGE5ZDA5NTNjODk1OWFlYjE5YmE1NWY1YzA0YjBhNTRjODQ4MjNjIiwicHJlZml4ZWRBZGRyZXNzIjoiZW9hOjB4NDhhOWQwOTUzYzg5NTlhZWIxOWJhNTVmNWMwNGIwYTU0Yzg0ODIzYyIsInR5cGUiOiJFT0EifX0seyJhY2NvdW50Ijp7ImFkZHJlc3MiOiIweGU0Mzg3ZDRlNDVmNjUyNDBkYWFmNWUwNDZkNWFlNTkyNTY2YTUwNzYiLCJjaGFpbiI6MTAwLCJwcmVmaXhlZEFkZHJlc3MiOiJnbm86MHhlNDM4N2Q0ZTQ1ZjY1MjQwZGFhZjVlMDQ2ZDVhZTU5MjU2NmE1MDc2IiwidGhyZXNob2xkIjoyLCJ0eXBlIjoiU0FGRSJ9LCJjb25uZWN0aW9uIjp7ImZyb20iO …

fix(pilot-app): error on certain transaction simulations on submit

---

deployables/app/app/balances/server/getTokenBalances.ts
deployables/app/app/balances/types.ts
deployables/app/app/routes/$address.$chainId/balances.ts
deployables/app/app/routes/tokens/balances/balances.tsx

fix(pilot-app): adjust code for possible null usd value

---

deployables/app/app/routes/submit/$route.$transactions/sign.tsx

fix: toast notification

---

deployables/app/app/routes/create/create.spec.ts
deployables/app/app/routes/edit/list-routes.spec.ts
deployables/app/app/routes/edit/list-routes.tsx
deployables/app/db/access/getAccounts.ts
deployables/app/db/schema/index.ts
deployables/app/test-utils/db/accountFactory.ts
deployables/app/test-utils/db/userFactory.ts
deployables/app/test-utils/db/walletFactory.ts

feat(pilot-app): show currently active wallet

---

deployables/app/app/components/AvatarInput.tsx
deployables/app/app/components/InitiatorInput.tsx

fix(pilot-app): update inputs after load to reflect default value correctly

---

deployables/app/app/routes/create/create.tsx

fix: load accounts reachable from current wallet

---

.github/workflows/live-tests.yaml
deployables/app/e2e/utils/fixture.ts
event-file.json
turbo.json

chore: run e2e tests against latest public release

---

deployables/app/app/routes/sign/$route.$transactions/sign.tsx
deployables/app/app/routes/sign/SignTransaction.tsx
deployables/app/app/routes/sign/account.$accountId.$transactions/sign.tsx
deployables/app/app/routes/sign/table/TokenTransferTable.tsx
deployables/app/app/utils/jsonRpcProvider.ts
deployables/extension/src/panel/providers/fork-provider/readOnlyProvider.ts
packages/chains/src/const.ts
packages/safe/src/kits.ts

chore(zodiac-os): remove safe multisig wait

---

deployables/app/app/routes/errorBoundary.tsx

chore: expose error message even outside dev environments

---

deployables/app/app/components/pilotStatus/PilotStatusContext.tsx
deployables/app/app/components/pilotStatus/useDisconnectWhenUnreachable.ts
deployables/app/app/components/pilotStatus/usePingWhileDisconnected.ts
deployables/app/app/routes/layout.tsx
deployables/extension/src/background/companionEnablement.spec.ts
deployables/extension/src/companion/contentScripts/main.spec.ts
deployables/extension/src/panel/companion/CompanionAppSupport.tsx
deployables/extension/src/panel/companion/getUser.ts
deployables/extension/src/panel/companion/index.ts
deployables/extension/src/panel/pages/$activeAccountId/AccountActions.tsx
deployables/extension/src/panel/pages/$activeAccountId/AccountSelect.tsx
deployables/extension/src/panel/pages/$activeAccountId/ActiveAccount.spec.ts
deployables/extension/src/panel/pages/$activeAccountId/ActiveAccount.tsx
deployables/extension/src/panel/pages/$activeAccountId/clear-transactions.$newActiveAccountId/ClearTransactions.spec.ts
deployables/extension/src/panel/pages/$activeAccountId/intents.ts
deployables/extension/src/panel/pages/$activeAccountId/transactions/Transactions.spec.ts
deployables/extension/src/panel/pages/$activeAccountId/transactions/Transactions.tsx
deployables/extension/src/panel/pages/$activeAccountId/transactions/intents.ts
deployables/extension/src/panel/pages/Root.spec.ts
deployables/extension/src/panel/pages/Root.tsx
deployables/extension/src/panel/pages/useRevalidateOnSignIn.ts
deployables/extension/src/panel/routes.tsx
packages/messages/src/companionApp.ts

feat(zodiac-os,extension): refresh extension when user signs in

---

deployables/extension/src/background/sessionTracking.spec.ts
deployables/extension/src/background/sessionTracking.ts
deployables/extension/src/panel/port-handling/usePilotPort.ts
packages/messages/src/extension/connect.ts

fix(pilot-extension): send keep alive message through runtime port

---

deployables/extension/src/background/rpcTracking.ts
deployables/extension/src/inject/contentScript/main.ts
deployables/extension/src/inject/contentScript/probeChainId.ts

chore(extension): extend logging around rpc call tracking

---

deployables/app/app/routes.ts
deployables/app/app/routes/robots.ts

feat: add robots.txt

---

deployables/extension/src/panel/pages/$activeAccountId/transactions/Transactions.tsx
deployables/extension/src/panel/pages/Root.spec.ts
deployables/extension/src/panel/pages/Root.tsx
deployables/extension/src/panel/pages/useDeleteRoute.ts

fix: clear transactions when account was deleted

---

deployables/app/app/simulation/server/extractApprovalsFromSimulation.ts

fix: accept more than 3 inputs for approval logs

---

deployables/app/app/simulation/server/simulateTransactionBundle.ts
deployables/app/app/simulation/types.ts

fix: handle null values in simulated transactions

---

deployables/extension/src/panel/pages/$activeAccountId/clear-transactions.$newActiveAccountId/useClearTransactions.ts
deployables/extension/src/panel/pages/$activeAccountId/transactions/Remove.tsx
deployables/extension/src/panel/pages/$activeAccountId/transactions/Submit.tsx
deployables/extension/src/panel/pages/$activeAccountId/transactions/Transactions.tsx
deployables/extension/src/panel/providers-ui/ProvideProvider.tsx
deployables/extension/src/panel/state/actions.ts
deployables/extension/src/panel/state/index.tsx
deployables/extension/src/panel/state/provideState.tsx
deployables/extension/src/panel/state/reducer.spec.ts
deployables/extension/src/panel/state/reducer.ts
deployables/extension/src/panel/transactionTranslations/useApplicableTranslation.ts
deployables/extension/src/panel/transactionTranslations/useGloballyApplicableTranslation.ts

chore(extension): introduce enums for transaction types

---

deployables/app/app/routes.ts
deployables/app/app/routes/create/create.spec.ts
deployables/app/app/routes/create/create.tsx
deployables/app/app/routes/edit/list-routes.tsx
deployables/app/app/routes/layout.tsx
deployables/app/app/routes/legacy-redirects/old-new-route-redirect.ts
deployables/app/e2e/create/createRoute.spec.ts
deployables/app/e2e/smoketest.spec.ts

feat(zodiac-os): create account

---

deployables/extension/src/inject/contentScript/probeChainId.spec.ts
deployables/extension/src/inject/contentScript/probeChainId.ts

fix(pilot-extension): make chain id probing have some known networks

---

deployables/app/app/routes/account/edit.spec.ts
deployables/app/app/routes/account/edit.tsx
packages/ui/src/forms/InlineForm.tsx

feat(zodiac-os): create wallets on the fly from the account edit view

---

deployables/extension/src/panel/accounts/useActivateAccount.ts
deployables/extension/src/panel/pages/$activeAccountId/clear-transactions.$newActiveAccountId/ClearTransactions.tsx
deployables/extension/src/panel/pages/$activeAccountId/transactions/Transactions.tsx
deployables/extension/src/panel/routes.tsx

fix(pilot-extension): create account

---

deployables/app/app/routes/account/routes.spec.ts
deployables/app/app/routes/account/routes.tsx

feat(zodiac-os): switch default route

---

packages/db/schema/index.ts
packages/db/src/access/transactions/saveTransaction.ts
packages/db/supabase/migrations/0033_store-snapshot-for-transactions.sql
packages/db/supabase/migrations/meta/0033_snapshot.json
packages/db/supabase/migrations/meta/_journal.json
packages/db/test-utils/factories/signedTransactionFactory.ts

feat(zodiac-os): store route snapshot

---

deployables/app/app/routes/account/routes.spec.ts
deployables/app/app/routes/account/routes.tsx
deployables/app/app/routes/edit/RemoteAccount.tsx
deployables/app/app/routes/edit/list-accounts.spec.ts
deployables/app/app/routes/edit/list-accounts.tsx
deployables/app/app/routes/sign/proposal/sign.tsx
packages/db/package.json
packages/db/schema/index.ts
packages/db/src/access/routes/createRoute.ts
packages/db/src/access/routes/getRoutes.spec.ts
packages/db/src/access/routes/getRoutes.ts
packages/db/supabase/migrations/0034_add user reference to route.sql
packages/db/supabase/migrations/meta/0034_snapshot.json
packages/db/supabase/migrations/meta/_journal.json
packages/db/test-utils/factories/routeFactory.ts
packages/db/test-utils/setupTests.ts

chore(zodiac-os): remove pilot signer from accounts list

---

deployables/app/app/routes-ui/Routes.tsx
deployables/app/app/routes.ts
deployables/app/app/routes/account/routes.tsx
deployables/app/app/routes/edit/list-accounts.tsx
deployables/app/app/routes/extension/activeRoute.ts
deployables/app/app/routes/sign/$route.$transactions/sign.tsx
deployables/app/app/routes/sign/account.$accountId.$transactions/sign.spec.ts
deployables/app/app/routes/sign/proposal/load-default-route.spec.ts
deployables/app/app/routes/sign/proposal/load-default-route.ts
deployables/app/app/routes/sign/proposal/load-default-route.tsx
deployables/app/app/routes/sign/proposal/sign.spec.ts
deployables/app/app/routes/sign/proposal/sign.tsx
deployables/app/app/routes/sign/sections/ReviewAccountSection.tsx
packages/db/src/access/routes/findDefaultRoute.ts
packages/db/src/access/routes/getRoute.ts
packages/ui/src/inputs/Labeled.tsx

feat(zodiac-os): route param for sign page

---

.github/workflows/landing-page-preview.yaml
deployables/extension/src/background/rpcRedirects/rpcTracking.spec.ts
deployables/extension/src/background/rpcRedirects/rpcTracking.ts
deployables/landing-page/README.md
deployables/vnet-api/.env.sample
deployables/vnet-api/package.json
deployables/vnet-api/src/index.ts
packages/env/src/getVnetApiUrl.ts
pnpm-lock.yaml

fixes some CORS issues with the RPC proxy. also lays some groundwork for proxying websocket json rpc to implement #186 in the future.

fix(pilot-extension): CORS issues with RPC proxy

---

deployables/extension/src/panel/pages/$activeAccountId/transactions/Transactions.spec.ts
deployables/extension/src/panel/pages/$activeAccountId/transactions/Transactions.tsx

fix(pilot-extension): do not clear transactions on safe account update

---

deployables/app/app/routes/accounts/add-route.tsx
deployables/app/app/routes/accounts/routes.spec.ts
deployables/app/app/routes/accounts/routes.tsx
packages/modules/src/ser-kit/index.ts
packages/modules/src/ser-kit/queryInitiators.ts

chore(zodiac-os): safely query initiators from ser-kit

---

packages/db/package.json
packages/db/schema/index.ts
packages/db/supabase/migrations/0051_add nonce to users.sql
packages/db/supabase/migrations/meta/0051_snapshot.json
packages/db/supabase/migrations/meta/_journal.json
packages/db/supabase/seed.sql
packages/db/test-utils/factories/userFactory.ts
pnpm-lock.yaml

feat(zodiac-os): add nonce to users

---

deployables/app/app/routes/roles/add-asset.tsx
deployables/app/app/routes/roles/create.spec.ts
deployables/app/app/routes/roles/edit.spec.ts
deployables/app/app/routes/roles/edit.tsx
packages/db/src/access/roles/getActivatedAccounts.ts
packages/db/src/access/roles/getRoleMembers.ts

chore(zodiac-os): simplify some retrieval apis

---

deployables/app/app/routes/roles/AllowanceIntervalSelect.tsx
deployables/app/app/routes/roles/add-asset.tsx
deployables/app/app/routes/roles/edit-asset.tsx
deployables/app/app/routes/roles/edit.spec.ts
packages/db/schema/createRandomString.ts
packages/db/schema/index.ts
packages/db/src/access/roles/createRoleActionAssets.ts
packages/db/src/access/roles/updateAllowance.ts
packages/db/supabase/migrations/0058_add allowance key.sql
packages/db/supabase/migrations/meta/0058_snapshot.json
packages/db/supabase/migrations/meta/_journal.json
packages/db/test-utils/factories/roleActionAssetFactory.ts
packages/schema/src/index.ts
packages/schema/src/roles/allowances.ts
packages/schema/src/roles/index.ts

feat(zodiac-os): add allowance key when creating an asset

---

deployables/app/app/routes/sign/sections/ReviewAccountSection.tsx
deployables/extension/src/panel/execution-routes/findAdHocRoute.ts
deployables/extension/src/panel/execution-routes/index.ts
deployables/extension/src/panel/pages/$activeAccountId/AccountActions.tsx
deployables/extension/src/panel/providers/fork-provider/ForkProvider.ts
deployables/extension/src/panel/providers/fork-provider/TenderlyProvider.tsx
deployables/extension/src/panel/transactions/MockProvider.ts
deployables/extension/src/panel/transactions/ProvideForkProvider.tsx
deployables/extension/src/panel/transactions/useExecutionTracking.ts
deployables/extension/src/panel/transactions/useForkTracking.spec.tsx
deployables/extension/src/panel/transactions/useForkTracking.ts

implements #2004, this will be used for spoofing ERC20 token balances for Railgun mechs

feat(pilot-extension): support passing setup calls for simulation forks with launch routes 

---

deployables/app/app/routes/$address.$chainId/balances.ts
deployables/app/app/vnet/server/applyDeltaToBalances.ts
deployables/app/app/vnet/server/getVnetTransactionDelta.ts
deployables/app/app/vnet/server/getVnetTransactions.ts
deployables/app/app/vnet/server/processTransferLogs.spec.ts
deployables/app/app/vnet/server/processTransferLogs.ts

feat(zodiac-os): reflect spoofed ERC20 balances

---

deployables/app/app/routes/sign/proposal/sign.spec.ts
deployables/app/app/routes/sign/proposal/sign.tsx
packages/db/schema/index.ts
packages/db/supabase/migrations/0069_add callback to proposal.sql
packages/db/supabase/migrations/meta/0069_snapshot.json
packages/db/supabase/migrations/meta/_journal.json
packages/db/test-utils/factories/transactionProposalFactory.ts

feat(zodiac-os): store callback for proposal on proposal

---

deployables/app/app/routes/roles/deploy-role.spec.ts
deployables/app/app/routes/roles/deploy-role.tsx
deployables/app/app/routes/sign/proposal/load-default-route.spec.ts
deployables/app/app/routes/sign/proposal/load-default-route.tsx
packages/db/package.json
packages/db/schema/index.ts
packages/db/src/access/transactions/proposeTransaction.ts
packages/db/supabase/migrations/0073_add route id to proposal.sql
packages/db/supabase/migrations/meta/0073_snapshot.json
packages/db/supabase/migrations/meta/_journal.json
packages/db/test-utils/factories/transactionProposalFactory.ts

feat(zodiac-os): route selection on deploy page
